
# setup report
configfile: "config/config.yaml"

# load rules
include: "rules/common.smk"
include: "rules/preprocessing.smk"
include: "rules/tune_hyper_parameters.smk"
include: "rules/validate_algorithm.smk"
include: "rules/evaluate_algorithm.smk"

# target rules
rule all:
    input:
        get_final_output()


