from snakemake.io import expand
from snakemake.utils import min_version

# Set the minimum snakemake version required
min_version("6.4.1")

# setup report
configfile: "config/config.yaml"

# load rules
include: "rules/common.smk"
include: "rules/preprocessing.smk"
include: "rules/tune_hyper_parameters.smk"
include: "rules/train_algorithm.smk"
include: "rules/evaluate_algorithm.smk"

# target rules
rule all:
    input:
        get_final_output()

